defaults:
  - _base_ # we can extend fp16+peft as a base here
  - _self_
  - override launcher: process

experiment_name: fp16+peft+gptq-4bit

backend:
  no_weights: true
  quantization_scheme: gptq
  quantization_config:
    bits: 4
    disable_exllama: true
  peft_strategy: lora
  peft_config:
    task_type: CAUSAL_LM
