defaults:
  - _base_ # we can extend fp16+peft as a base here
  - _self_
  - override launcher: torchrun

experiment_name: fp16+peft+gptq-4bit

launcher:
  nproc_per_node: 2

backend:
  device_ids: 0,1
  no_weights: true
  quantization_scheme: gptq
  quantization_config:
    bits: 4
    disable_exllama: true
  peft_strategy: lora
  peft_config:
    task_type: CAUSAL_LM
