defaults:
  - _base_ # we can also extend fp16 as a base here
  - _self_
  - override launcher: process

experiment_name: fp16+peft

backend:
  peft_strategy: lora
  peft_config:
    task_type: CAUSAL_LM
