defaults:
  - _base_
  - _self_
  - override launcher: torchrun

experiment_name: fp16+fsdp=2

launcher:
  nproc_per_node: 2

backend:
  device_ids: 0,1

benchmark:
  training_arguments:
    fsdp: full_shard
