defaults:
  - _base_
  - _self_
  - override launcher: torchrun

experiment_name: fp16+peft+dp=2

launcher:
  nproc_per_node: 2

backend:
  device_ids: 0,1
  peft_strategy: lora
  peft_config:
    task_type: CAUSAL_LM
