defaults:
  - backend: tensorrt-llm # default backend
  # order of inheritance, last one overrides previous ones
  - _base_ # inherits from base config
  - _inference_ # inherits from inference config
  - _cuda_ # inherits from cpu config
  - _self_ # hydra 1.1 compatibility

benchmark:
  input_shapes:
    batch_size: 1

backend:
  model: TinyLlama/TinyLlama-1.1B-step-50K-105b

experiment_name: tensorrt_llm
