defaults:
  - _base_
  - _self_
  - override launcher: torchrun

experiment_name: fp16+bt+tp=2

launcher:
  nproc_per_node: 2

backend:
  device_ids: 0,1
  to_bettertransformer: true
  deepspeed_inference: true
  deepspeed_inference_config:
    tensor_parallel:
      tp_size: 2
