defaults:
  - backend: pytorch
  - bge_base_config
  - _self_

hydra:
  sweeper:
    params:
      benchmark.input_shapes.batch_size: 1
      benchmark.input_shapes.sequence_length: 16,32,64,128,256,512

experiment_name: bge_seq_len_sweep_baseline
