defaults:
  - backend: pytorch # default backend
  - launcher: process # default launcher
  - benchmark: inference # default benchmark
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: pytorch_llama

backend:
  device: cuda
  device_ids: 0,1
  device_map: true
  model: TheBloke/Llama-2-70B-AWQ

launcher:
  device_isolation: true

benchmark:
  input_shapes:
    batch_size: 1
    sequence_length: 256

  generate_kwargs:
    max_new_tokens: 256
    min_new_tokens: 256

# hydra/cli specific configuration
hydra:
  run:
    # run directory where the logs and results will be stored
    dir: runs/${experiment_name}
  job:
    # change the working directory to the run directory
    chdir: true
    env_set:
      # set the environment variable to override benchmarks
      # that already have results saved in the results directory
      OVERRIDE_BENCHMARKS: 1
