defaults:
  - launcher: process
  - benchmark: inference
  - backend: tensorrt-llm
  - experiment # inheriting experiment schema
  - _self_ # for hydra 1.1 compatibility
  - override hydra/job_logging: colorlog # colorful logging
  - override hydra/hydra_logging: colorlog # colorful logging

experiment_name: trt_llama

backend:
  device: cuda
  device_ids: 0
  model: NousResearch/Llama-2-7b-hf

benchmark:
  input_shapes:
    batch_size: 1
    sequence_length: 64

  generate_kwargs:
    max_new_tokens: 64
    min_new_tokens: 64

# hydra/cli specific configuration
hydra:
  run:
    # run directory where the logs and results will be stored
    dir: runs/${experiment_name}
  job:
    # change the working directory to the run directory
    chdir: true
    env_set:
      # set the environment variable to override benchmarks
      # that already have results saved in the results directory
      OVERRIDE_BENCHMARKS: 1
